### ISSUE TITLE
LomiriForUbuntu.py: Don't hardcode paths, use relative locations in user's $HOME

### ISSUE THREAD

**Issue by sunweaver** [tari01/LomiriForUbuntu#2]
```
TEMP_PATH = "/home/tari/Desktop/tmp/LomiriForUbuntu"
CREDENTIALS_PATH = "/home/tari/Desktop/.LomiriForUbuntu.txt"
```
tststs...

And why not use $TMPDIR? (or what the standard var name for it is?)

**Comment by tari01** [comment]
Depending on the web environment, you may not have access to `/tmp`. This gives some flexibility.
